server:
  port: 8091

# spring
spring:
  application:
    name: expay-wallet-demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 日志
logging:
  level:
    com.star: debug
    org.springframework: warn





